#!/bin/bash -eEu
set -o pipefail

readonly FREEBSD_VER=13.1
readonly IMG_FILE=mfsbsd-mini-${FREEBSD_VER}-RELEASE-amd64.img
readonly IMG_URL=https://mfsbsd.vx.sk/files/images/${FREEBSD_VER%%.*}/amd64/${IMG_FILE}

fail() {
  printf '%s. Use "--help" for syntax. Terminating.\n' "$*"
  exit 1
}

syntax() {
  cat <<-EOF >&2
	$(basename "$0") DEV

	This will install mfsBSD mini on DEV. Use 'dmesg | tail' can tell you the name of
	the device if it was just plugged in.
	EOF

  exit 0
}

[[ -n "${1:-}" ]] || fail 'Expected name of device'
[[ $1 != '-h' && "$1" != '--help' ]] || syntax
[[ -z "${2:-}" ]] || fail 'Only expecting one parameter'

readonly DEV="$1"

# 1. Fetch mfsBSD image, if not done already
[[ -f "$IMG_FILE" ]] || curl --location --remote-name "$IMG_URL"

# 2. Write to device
set -x # Make sure user knows what their password allows
sudo dd if="$IMG_FILE" of="$DEV" bs=1M
sync

set +x
printf '%s\n' "Image created successfully on device. Device can be safely removed."

